// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8Dy0FL6CRqjLYwZwbPAJVwnSa9dJhTU',
    appId: '1:106654082480:web:e832786ada2ae0dd992275',
    messagingSenderId: '106654082480',
    projectId: 'chatme-49a0e',
    authDomain: 'chatme-49a0e.firebaseapp.com',
    databaseURL: 'https://chatme-49a0e-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-49a0e.appspot.com',
    measurementId: 'G-Q2FSSS088S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0LDtnMuaL2NmujsGKLp3o-olRaSKCpC0',
    appId: '1:106654082480:android:637c745fcb445136992275',
    messagingSenderId: '106654082480',
    projectId: 'chatme-49a0e',
    databaseURL: 'https://chatme-49a0e-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-49a0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS2jEzWb78uqheYGeTK4sROfqBvC3yTog',
    appId: '1:106654082480:ios:7d0d49e8e12d5192992275',
    messagingSenderId: '106654082480',
    projectId: 'chatme-49a0e',
    databaseURL: 'https://chatme-49a0e-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-49a0e.appspot.com',
    iosBundleId: 'com.chatme.arqonics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS2jEzWb78uqheYGeTK4sROfqBvC3yTog',
    appId: '1:106654082480:ios:84ce27468542416c992275',
    messagingSenderId: '106654082480',
    projectId: 'chatme-49a0e',
    databaseURL: 'https://chatme-49a0e-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-49a0e.appspot.com',
    iosBundleId: 'com.example.chatMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF8Dy0FL6CRqjLYwZwbPAJVwnSa9dJhTU',
    appId: '1:106654082480:web:1db56e6861161952992275',
    messagingSenderId: '106654082480',
    projectId: 'chatme-49a0e',
    authDomain: 'chatme-49a0e.firebaseapp.com',
    databaseURL: 'https://chatme-49a0e-default-rtdb.firebaseio.com',
    storageBucket: 'chatme-49a0e.appspot.com',
    measurementId: 'G-G8HVBKZNWX',
  );
}
